# Generated by Django 5.0.7 on 2024-07-29 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('movie_id', models.IntegerField(default=None)),
                ('overview', models.TextField(default=None)),
                ('genres', models.TextField(blank=True)),
                ('cast', models.CharField(blank=True, max_length=600, null=True)),
                ('crew', models.CharField(blank=True, max_length=200, null=True)),
                ('production_companies', models.CharField(blank=True, max_length=500, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seat_Arrangement',
            fields=[
                ('id', models.AutoField(auto_created=True, db_index=True, primary_key=True, serialize=False)),
                ('no_seats', models.IntegerField()),
                ('seat_arrangement', models.JSONField()),
                ('no_rows', models.IntegerField()),
                ('no_cols', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SeatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, db_index=True, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.BooleanField(default=True)),
                ('place', models.CharField(max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('place', models.CharField(max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('payment_id', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seats', models.ManyToManyField(to='booking.seattype')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.show')),
                ('theatre', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='booking.theatre')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='SeatId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=50, null=True)),
                ('number', models.CharField(max_length=50, null=True)),
                ('type', models.ManyToManyField(blank=True, to='booking.seattype', verbose_name='seat_type')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.seatid')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.theatre')),
            ],
        ),
        migrations.CreateModel(
            name='MovieHall',
            fields=[
                ('id', models.AutoField(auto_created=True, db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('capacity', models.IntegerField()),
                ('seat_arrangement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.seat_arrangement')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.theatre')),
            ],
        ),
        migrations.CreateModel(
            name='TheatreMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, db_index=True, primary_key=True, serialize=False)),
                ('release_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.movies')),
                ('movie_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.moviehall')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.theatre')),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='theatre_movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.theatremovie'),
        ),
    ]
