# Generated by Django 5.0.7 on 2024-07-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='type',
            field=models.ManyToManyField(blank=True, to='booking.seattype', verbose_name='seat_type'),
        ),
    ]
