# Generated by Django 5.0.7 on 2024-07-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviehall',
            name='id',
            field=models.CharField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
