# Generated by Django 5.0.7 on 2024-07-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_seat_number_seat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='cast',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
