# Generated by Django 5.0.7 on 2024-07-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_moviehall_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theatremovie',
            name='id',
            field=models.CharField(auto_created=True, db_index=True, primary_key=True, serialize=False),
        ),
    ]
