# Generated by Django 5.0.7 on 2024-07-28 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_movies_cast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat_Arrangement',
            fields=[
                ('id', models.AutoField(auto_created=True, db_index=True, primary_key=True, serialize=False)),
                ('no_seats', models.IntegerField()),
                ('seat_arrangement', models.JSONField()),
                ('no_rows', models.IntegerField()),
                ('no_cols', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieHall',
            fields=[
                ('id', models.AutoField(auto_created=True, db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('capacity', models.IntegerField()),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.theatre')),
                ('seat_arrangement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.seat_arrangement')),
            ],
        ),
    ]
