# Generated by Django 5.0.7 on 2024-07-30 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_theatremovie_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='seat_id',
        ),
        migrations.AddField(
            model_name='seat',
            name='movie_hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.moviehall'),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_arrangement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.seat_arrangement'),
        ),
        migrations.AddField(
            model_name='seat',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seat',
            name='id',
            field=models.AutoField(db_index=True, default=None, primary_key=True, serialize=False),
        ),
    ]
