# Generated by Django 5.0.7 on 2024-07-28 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_seat_arrangement_moviehall'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheatreMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, db_index=True, primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.movies')),
                ('movie_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.moviehall')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.theatre')),
            ],
        ),
    ]
