# Generated by Django 5.0.7 on 2024-07-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_seat_seat_id_seat_movie_hall_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='seat_id',
            field=models.JSONField(default=dict),
        ),
    ]
