# Generated by Django 5.0.7 on 2024-07-28 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_theatremovie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='column',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='number',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='row',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='type',
        ),
        migrations.RemoveField(
            model_name='show',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='show',
            name='theatre',
        ),
        migrations.RemoveField(
            model_name='theatre',
            name='theatre_description',
        ),
        migrations.RemoveField(
            model_name='theatremovie',
            name='date',
        ),
        migrations.RemoveField(
            model_name='theatremovie',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='theatremovie',
            name='start_time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='theatre',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='booking.theatre'),
        ),
        migrations.AddField(
            model_name='show',
            name='theatre_movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.theatremovie'),
        ),
        migrations.AddField(
            model_name='theatremovie',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='theatremovie',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='id',
            field=models.AutoField(auto_created=True, db_index=True, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='SeatId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=50, null=True)),
                ('number', models.CharField(max_length=50, null=True)),
                ('type', models.ManyToManyField(blank=True, to='booking.seattype', verbose_name='seat_type')),
            ],
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.seatid'),
        ),
    ]
