# Generated by Django 5.0.6 on 2024-06-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_alter_rec_review_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('movie_id', models.IntegerField(default=None)),
                ('overview', models.TextField(default=None)),
                ('cast', models.CharField(max_length=200)),
                ('crew', models.CharField(max_length=100)),
                ('production_companies', models.CharField(max_length=200)),
                ('genres', models.ManyToManyField(to='recommendation.genre')),
            ],
        ),
    ]
