# Generated by Django 5.0.6 on 2024-06-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_genre_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='genres',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='movies',
            name='genres',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
