# Generated by Django 5.0.6 on 2024-06-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0005_alter_movies_production_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='cast',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movies',
            name='production_companies',
            field=models.TextField(),
        ),
    ]
