# Generated by Django 5.0.6 on 2024-06-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0007_recommendationlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.TextField(),
        ),
    ]
