# Generated by Django 5.0.6 on 2024-06-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0008_alter_movies_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='crew',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
