# Generated by Django 5.0.6 on 2024-07-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0009_alter_movies_crew'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='runtime',
            field=models.IntegerField(default=100),
        ),
    ]
