# Generated by Django 5.0.6 on 2024-07-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_seattype_alter_seat_price_seat_seat_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='seat',
        ),
        migrations.AddField(
            model_name='reservation',
            name='seats',
            field=models.ManyToManyField(to='booking.seat'),
        ),
    ]
